import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    hero_eyebrow: "Carbon Market • Daily Fresh",
    hero_heading: "Fresh from the vendors of Carbon Market.",
    hero_sub: "Locally sourced produce, meat, and seafood.",
    search_placeholder:
      "Search for merchants or carrots, seafood, organic beef…",
    find_deals: "Find deals near you →",
    browse_merchant: "Browse by Merchant →",
    latest_deals: "Latest Deals",
    latest_deals_sub: "The latest deals from our selection",
    browse_category: "Browse by Category",
    browse_merchants: "Browse Merchants",
    no_products: "No products found in this category.",
    no_merchants: "No merchants found in this category.",
    loading_listings: "Loading listings…",
    loading_merchants: "Loading merchants…",
    view_all: "View All",
    show_less: "Show Less ↑",
    items: "items",
    item: "item",
    in: "in",
    vendor_dashboard: "Vendor Dashboard",
    welcome_back: "Welcome back",
    dashboard_sub: "Manage your stall and listings from here.",
    add_listing: "+ Add New Listing",
    view_listings: "View My Listings",
    edit_profile: "Edit Profile",
    change_pass_title: "Set Your Password",
    change_pass_sub:
      "This is your first login. Please set a new password before continuing.",
    new_password: "New Password",
    new_password_placeholder: "New password",
    confirm_password: "Confirm Password",
    confirm_password_placeholder: "Confirm password",
    saving: "Saving...",
    set_password: "Set Password",
    passwords_no_match: "Passwords do not match.",
    back: "← Back",
    create_listing_title: "Create New Listing",
    create_listing_sub: "Add a new product to your stall.",
    create_listing_btn: "Create Listing",
    save_listing_btn: "Save Listing",
    delete_listing_btn: "Delete Listing",
    confirm_delete_listing: "Are you sure you want to delete this listing?",
    quantity_zero: "Quantity can't be 0!",
    price_zero: "Original price can't be 0!",
    discounted_price_invalid:
      "Discounted price can't be higher than or equal to original price!",
    fields_required: "All fields are required! Please check your inputs.",
    error_prefix: "Error: ",
    edit_profile_title: "Edit your Profile",
    clear_pin: "Clear pin",
    error_user_not_found: "User details cannot be retrieved",
    error_stall_name_required: "Stall Name is required",
    error_market_location_required: "Market Location is required",
    error_phone_required: "Phone Number is required",
    error_schedule_required: "Please select at least one operating day",
    error_hours_required: "Please enter operating hours for all selected days",
    my_listings: "MY LISTINGS:",
    dashboard_edit_profile: "Edit Profile",
    dashboard_add_listing: "+ Add new listing",
    dashboard_loading: "Loading listings...",
    dashboard_error: "Failed to load your listings. Please try again.",
    no_listings_search: "No listings match your search.",
    no_listings_yet: "You have no listings yet.",
    create_first_listing: "Create your first listing",
    confirm_sold_out: "Mark as sold out?",
    failed_sold_out: "Failed to mark as sold out. Please try again.",
    map_search_placeholder: "Search a store name...",
    map_loading: "Loading map...",
    stall_photo: "Stall Photo:",
    sold_out: "Sold Out",
    view_store: "View Store",
    vl_loading: "Loading...",
    vl_error: "Could not load this listing.",
    vl_not_found: "Listing not found.",
    vl_go_back: "← Go Back",
    vl_back_marketplace: "← Back to Marketplace",
    vl_produce: "PRODUCE",
    vl_general: "GENERAL",
    vl_quantity: "QUANTITY",
    vl_type: "TYPE",
    vl_listed_on: "LISTED ON",
    vl_product_details: "Product Details",
    vl_edit_listing: "Edit Listing",
    vl_view_merchant: "View Merchant",
    vl_stall_location: "Stall Location",
    vl_location_not_set: "Location not set",
  },
  ceb: {
    hero_eyebrow: "Carbon Market • Sariwa Matag Adlaw",
    hero_heading: "Sariwa gikan sa mga tindera sa Carbon Market.",
    hero_sub: "Lokal nga produkto, karne, ug isda.",
    search_placeholder: "Pangita ug mga tindera, karot, isda, organikong baka…",
    find_deals: "Pangita ug deals duol nimo →",
    browse_merchant: "Pangita ug Tindera →",
    latest_deals: "Bag-ong mga Deal",
    latest_deals_sub: "Ang pinakabag-o nga mga deal gikan sa among pagpili",
    browse_category: "I-browse pa Kategorya",
    browse_merchants: "Pangita ug mga Tindera",
    no_products: "Walay produkto sa kining kategorya.",
    no_merchants: "Walay tindera sa kining kategorya.",
    loading_listings: "Gi-load ang mga paninda…",
    loading_merchants: "Gi-load ang mga tindera…",
    view_all: "Tan-awa Tanan",
    show_less: "Ipakita Ang Pipila ↑",
    items: "mga butang",
    item: "butang",
    in: "sa",
    vendor_dashboard: "Dashboard sa Tindera",
    welcome_back: "Maayong pagbalik",
    dashboard_sub: "Huwata ang imong tindahan ug mga paninda dinhi.",
    add_listing: "+ Pagdugang og Bag-ong Paninda",
    view_listings: "I-tan-aw ang Akong Paninda",
    edit_profile: "I-edit ang Profile",
    change_pass_title: "Itakda ang Imong Password",
    change_pass_sub:
      "Kini ang imong unang pag-login. Palihug itakda ang bag-ong password sa dili pa magpadayon.",
    new_password: "Bag-ong Password",
    new_password_placeholder: "Bag-ong password",
    confirm_password: "Kumpirmahon ang Password",
    confirm_password_placeholder: "Kumpirmahon ang password",
    saving: "Gina-save...",
    set_password: "Itakda ang Password",
    passwords_no_match: "Ang mga password dili magkatugma.",
    back: "← Balik",
    create_listing_title: "Paghimo og Bag-ong Listing",
    create_listing_sub: "Pagdugang og bag-ong produkto sa imong tindahan.",
    create_listing_btn: "Paghimo og Listing",
    save_listing_btn: "I-save ang Listing",
    delete_listing_btn: "Papason ang Listing",
    confirm_delete_listing:
      "Sigurado ka bang gusto mong papason kining listing?",
    quantity_zero: "Ang kantidad dili pwedeng zero!",
    price_zero: "Ang orihinal nga presyo dili pwedeng zero!",
    discounted_price_invalid:
      "Ang discounted nga presyo dili pwedeng mas taas o pareho sa orihinal nga presyo!",
    fields_required:
      "Kinahanglan ang tanan nga patlang! Palihug i-check ang imong mga input.",
    error_prefix: "Sayop: ",
    edit_profile_title: "I-edit ang Imong Profile",
    clear_pin: "Tanggala ang pin",
    error_user_not_found: "Dili ma-kuha ang detalye sa gumagamit",
    error_stall_name_required: "Kinahanglan ang Ngalan sa Tindahan",
    error_market_location_required: "Kinahanglan ang Lokasyon sa Merkado",
    error_phone_required: "Kinahanglan ang Numero sa Telepono",
    error_schedule_required:
      "Palihug pili og labing menos usa ka adlaw sa operasyon",
    error_hours_required:
      "Palihug isulod ang oras sa operasyon alang sa tanan nga piniling adlaw",
    my_listings: "AKO NGA MGA LISTING:",
    dashboard_edit_profile: "I-edit ang Profile",
    dashboard_add_listing: "+ Magdugang og bag-ong listing",
    dashboard_loading: "Gi-load ang mga listing...",
    dashboard_error:
      "Napakyas ang pag-load sa imong mga listing. Palihug sulayi pag-usab.",
    no_listings_search: "Walay listing nga nagtugma sa imong pagpangita.",
    no_listings_yet: "Wala ka pay mga listing.",
    create_first_listing: "Paghimo sa imong unang listing",
    confirm_sold_out: "Markahan nga sold out?",
    failed_sold_out:
      "Napakyas ang pagmarka nga sold out. Palihug sulayi pag-usab.",
    map_search_placeholder: "Magpangita og ngalan sa tindahan...",
    map_loading: "Gi-load ang mapa...",
    stall_photo: "Litrato sa Tindahan:",
    sold_out: "Sold Out",
    view_store: "Tan-awa ang Tindahan",
    vl_loading: "Gi-load...",
    vl_error: "Dili ma-load kining listing.",
    vl_not_found: "Listing not found.",
    vl_go_back: "← Balik",
    vl_back_marketplace: "← Balik sa Merkado",
    vl_produce: "PRODUKTO",
    vl_general: "KINATIBUK-AN",
    vl_quantity: "KANTIDAD",
    vl_type: "KLASE",
    vl_listed_on: "GILISTA SA",
    vl_product_details: "Detalye sa Produkto",
    vl_edit_listing: "I-edit ang Listing",
    vl_view_merchant: "Tan-awa ang Tindera",
    vl_stall_location: "Lokasyon sa Tindahan",
    vl_location_not_set: "Wala pa ma-set ang lokasyon",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");
  const t = (key) => translations[lang][key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
