import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    hero_eyebrow: "Carbon Market • Daily Fresh",
    hero_heading: "Fresh from the vendors of Carbon Market.",
    hero_sub: "Locally sourced produce, meat, and seafood.",
    search_placeholder:
      "Search for merchants or carrots, seafood, organic beef…",
    find_deals: "Find deals near you →",
    browse_merchant: "Browse by Merchant →",
    latest_deals: "Latest Deals",
    latest_deals_sub: "The latest deals from our selection",
    browse_category: "Browse by Category",
    browse_merchants: "Browse Merchants",
    no_products: "No products found in this category.",
    no_merchants: "No merchants found in this category.",
    loading_listings: "Loading listings…",
    loading_merchants: "Loading merchants…",
    view_all: "View All",
    show_less: "Show Less ↑",
    items: "items",
    item: "item",
    in: "in",
    vendor_dashboard: "Vendor Dashboard",
    welcome_back: "Welcome back",
    dashboard_sub: "Manage your stall and listings from here.",
    add_listing: "+ Add New Listing",
    view_listings: "View My Listings",
    edit_profile: "Edit Profile",
    change_pass_title: "Set Your Password",
    change_pass_sub:
      "This is your first login. Please set a new password before continuing.",
    new_password: "New Password",
    new_password_placeholder: "New password",
    confirm_password: "Confirm Password",
    confirm_password_placeholder: "Confirm password",
    saving: "Saving...",
    set_password: "Set Password",
    passwords_no_match: "Passwords do not match.",
    back: "← Back",
    create_listing_title: "Create New Listing",
    create_listing_sub: "Add a new product to your stall.",
    create_listing_btn: "Create Listing",
    save_listing_btn: "Save Listing",
    delete_listing_btn: "Delete Listing",
    confirm_delete_listing: "Are you sure you want to delete this listing?",
    quantity_zero: "Quantity can't be 0!",
    price_zero: "Original price can't be 0!",
    discounted_price_invalid:
      "Discounted price can't be higher than or equal to original price!",
    fields_required: "All fields are required! Please check your inputs.",
    error_prefix: "Error: ",
    edit_profile_title: "Edit your Profile",
    clear_pin: "Clear pin",
    error_user_not_found: "User details cannot be retrieved",
    error_stall_name_required: "Stall Name is required",
    error_market_location_required: "Market Location is required",
    error_phone_required: "Phone Number is required",
    error_schedule_required: "Please select at least one operating day",
    error_hours_required: "Please enter operating hours for all selected days",
    my_listings: "MY LISTINGS:",
    dashboard_edit_profile: "Edit Profile",
    dashboard_add_listing: "+ Add new listing",
    dashboard_loading: "Loading listings...",
    dashboard_error: "Failed to load your listings. Please try again.",
    no_listings_search: "No listings match your search.",
    no_listings_yet: "You have no listings yet.",
    create_first_listing: "Create your first listing",
    confirm_sold_out: "Mark as sold out?",
    failed_sold_out: "Failed to mark as sold out. Please try again.",
    map_search_placeholder: "Search a store name...",
    map_loading: "Loading map...",
    stall_photo: "Stall Photo:",
    sold_out: "Sold Out",
    view_store: "View Store",
    vl_loading: "Loading...",
    vl_error: "Could not load this listing.",
    vl_not_found: "Listing not found.",
    vl_go_back: "← Go Back",
    vl_back_marketplace: "← Back to Marketplace",
    vl_produce: "PRODUCE",
    vl_general: "GENERAL",
    vl_quantity: "QUANTITY",
    vl_type: "TYPE",
    vl_listed_on: "LISTED ON",
    vl_product_details: "Product Details",
    vl_edit_listing: "Edit Listing",
    vl_view_merchant: "View Merchant",
    vl_stall_location: "Stall Location",
    vl_location_not_set: "Location not set",
    vm_loading_profile: "Loading merchant profile...",
    vm_merchant_not_found: "Merchant not found.",
    vm_located_in: "Located in",
    vm_schedule: "Schedule:",
    vm_closed: "CLOSED",
    vm_back: "Back",
    vm_featured_products: "Featured Products",
    vm_search_placeholder: "Search products...",
    vm_no_products: "No products found.",
    header_search_placeholder: "Search products…",
    header_vendor_map: "Vendor Map",
    header_my_listings: "My Listings",
    header_add_listing: "Add New Listing",
    header_login: "Log in to Sell",
    sign_in: "Sign in",
    email_placeholder: "Your email",
    password_placeholder: "Your password",
    forgot_password: "forgot your password?",
    processing: "Processing...",
    log_in: "Log In",
    admin_login: "Logging in as an administrator?",
    auth_modal_title: "Vendor Login",
    auth_modal_subtitle: "Manage your harvest and connect with customers.",
    lf_photo_title: "Product photo",
    lf_photo_sub: "Please add a photo for your product",
    lf_details_title: "Product Details",
    lf_details_sub: "Enter details about your product",
    lf_product_name: "Product Name",
    lf_product_name_placeholder: "e.g. Cabbage, Carrot, etc.",
    lf_quantity: "Quantity",
    lf_unit: "Unit",
    lf_product_type: "Product Type",
    lf_type_vegetable: "Vegetables",
    lf_type_fruit: "Fruit",
    lf_type_chicken: "Chicken",
    lf_type_pork: "Pork",
    lf_type_beef: "Beef",
    lf_type_seafood: "Seafood",
    lf_type_rice: "Rice",
    lf_pricing_title: "Pricing",
    lf_pricing_sub: "Enter your original and discounted prices",
    lf_has_discount: "Does your product have a discount?",
    lf_original_price: "Original Price",
    lf_discounted_price: "Discounted Price",
    lf_availability_title: "Availability",
    lf_availability_sub: "How long will this listing be available?",
    lf_availability_window: "Availability Window",
    lf_ends_today: "Ends Today",
    lf_1_day: "1 Day",
    lf_2_days: "2 Days",
    lf_3_days: "3 Days",
    li_no_discount: "No Discount",
    li_sold_out: "Sold Out",
    li_listed: "Listed",
    li_edit: "Edit",
    li_mark_sold_out: "Mark Sold Out",
    mi_loading: "Loading merchant details...",
    mi_no_photo: "No photo found",
    mi_market_location: "Market Location:",
    mi_contact: "Contact #:",
    mi_stall_location: "STALL LOCATION",
    pf_email: "Email Address",
    pf_stall_photo: "Stall Photo",
    pf_click_to_upload: "Click to upload photo",
    pf_stall_name: "Stall Name",
    pf_market_location: "Market Location / Section",
    pf_phone: "Phone Number",
    pf_what_selling: "What are you selling?",
    pf_unselect_all: "Unselect All",
    pf_select_all: "Select All",
    pf_operating_days: "Operating Days",
    pf_operating_hours: "Operating Hours",
    pf_creating: "Creating...",
    pf_saving: "Saving...",
    pf_create_profile: "Create Profile",
    pf_save_profile: "Save Profile",
    vh_vendor_dashboard: "Vendor Dashboard",
    vh_marketplace: "Marketplace",
    vh_notifications: "Notifications",
    vh_profile: "Profile",
    vh_log_out: "Log Out",
    you_are_here: "You are here",
    recenter_label: "Re-center map on my location",
    recenter_title: "Re-center",
    locating: "Locating you…",
  },
  ceb: {
    hero_eyebrow: "Carbon Market • Sariwa Matag Adlaw",
    hero_heading: "Sariwa gikan sa mga tindera sa Carbon Market.",
    hero_sub: "Lokal nga produkto, karne, ug isda.",
    search_placeholder: "Pangita ug mga tindera, karot, isda, organikong baka…",
    find_deals: "Pangita ug deals duol nimo →",
    browse_merchant: "Pangita ug Tindera →",
    latest_deals: "Bag-ong mga Deal",
    latest_deals_sub: "Ang pinakabag-o nga mga deal gikan sa among pagpili",
    browse_category: "I-browse pa Kategorya",
    browse_merchants: "Pangita ug mga Tindera",
    no_products: "Walay produkto sa kining kategorya.",
    no_merchants: "Walay tindera sa kining kategorya.",
    loading_listings: "Gi-load ang mga paninda…",
    loading_merchants: "Gi-load ang mga tindera…",
    view_all: "Tan-awa Tanan",
    show_less: "Ipakita Ang Pipila ↑",
    items: "mga butang",
    item: "butang",
    in: "sa",
    vendor_dashboard: "Dashboard sa Tindera",
    welcome_back: "Maayong pagbalik",
    dashboard_sub: "Huwata ang imong tindahan ug mga paninda dinhi.",
    add_listing: "+ Pagdugang og Bag-ong Paninda",
    view_listings: "I-tan-aw ang Akong Paninda",
    edit_profile: "I-edit ang Profile",
    change_pass_title: "Itakda ang Imong Password",
    change_pass_sub:
      "Kini ang imong unang pag-login. Palihug itakda ang bag-ong password sa dili pa magpadayon.",
    new_password: "Bag-ong Password",
    new_password_placeholder: "Bag-ong password",
    confirm_password: "Kumpirmahon ang Password",
    confirm_password_placeholder: "Kumpirmahon ang password",
    saving: "Gina-save...",
    set_password: "Itakda ang Password",
    passwords_no_match: "Ang mga password dili magkatugma.",
    back: "← Balik",
    create_listing_title: "Paghimo og Bag-ong Listing",
    create_listing_sub: "Pagdugang og bag-ong produkto sa imong tindahan.",
    create_listing_btn: "Paghimo og Listing",
    save_listing_btn: "I-save ang Listing",
    delete_listing_btn: "Papason ang Listing",
    confirm_delete_listing:
      "Sigurado ka bang gusto mong papason kining listing?",
    quantity_zero: "Ang kantidad dili pwedeng zero!",
    price_zero: "Ang orihinal nga presyo dili pwedeng zero!",
    discounted_price_invalid:
      "Ang discounted nga presyo dili pwedeng mas taas o pareho sa orihinal nga presyo!",
    fields_required:
      "Kinahanglan ang tanan nga patlang! Palihug i-check ang imong mga input.",
    error_prefix: "Sayop: ",
    edit_profile_title: "I-edit ang Imong Profile",
    clear_pin: "Tanggala ang pin",
    error_user_not_found: "Dili ma-kuha ang detalye sa gumagamit",
    error_stall_name_required: "Kinahanglan ang Ngalan sa Tindahan",
    error_market_location_required: "Kinahanglan ang Lokasyon sa Merkado",
    error_phone_required: "Kinahanglan ang Numero sa Telepono",
    error_schedule_required:
      "Palihug pili og labing menos usa ka adlaw sa operasyon",
    error_hours_required:
      "Palihug isulod ang oras sa operasyon alang sa tanan nga piniling adlaw",
    my_listings: "AKO NGA MGA LISTING:",
    dashboard_edit_profile: "I-edit ang Profile",
    dashboard_add_listing: "+ Magdugang og bag-ong listing",
    dashboard_loading: "Gi-load ang mga listing...",
    dashboard_error:
      "Napakyas ang pag-load sa imong mga listing. Palihug sulayi pag-usab.",
    no_listings_search: "Walay listing nga nagtugma sa imong pagpangita.",
    no_listings_yet: "Wala ka pay mga listing.",
    create_first_listing: "Paghimo sa imong unang listing",
    confirm_sold_out: "Markahan nga sold out?",
    failed_sold_out:
      "Napakyas ang pagmarka nga sold out. Palihug sulayi pag-usab.",
    map_search_placeholder: "Magpangita og ngalan sa tindahan...",
    map_loading: "Gi-load ang mapa...",
    stall_photo: "Litrato sa Tindahan:",
    sold_out: "Sold Out",
    view_store: "Tan-awa ang Tindahan",
    vl_loading: "Gi-load...",
    vl_error: "Dili ma-load kining listing.",
    vl_not_found: "Listing not found.",
    vl_go_back: "← Balik",
    vl_back_marketplace: "← Balik sa Merkado",
    vl_produce: "PRODUKTO",
    vl_general: "KINATIBUK-AN",
    vl_quantity: "KANTIDAD",
    vl_type: "KLASE",
    vl_listed_on: "GILISTA SA",
    vl_product_details: "Detalye sa Produkto",
    vl_edit_listing: "I-edit ang Listing",
    vl_view_merchant: "Tan-awa ang Tindera",
    vl_stall_location: "Lokasyon sa Tindahan",
    vl_location_not_set: "Wala pa ma-set ang lokasyon",
    vm_loading_profile: "Gi-load ang profile sa tindera...",
    vm_merchant_not_found: "Wala makit-i ang tindera.",
    vm_located_in: "Nahimutang sa",
    vm_schedule: "Iskedyul:",
    vm_closed: "SIRADO",
    vm_back: "Balik",
    vm_featured_products: "Mga Gipasiugda nga Produkto",
    vm_search_placeholder: "Mangita og mga produkto...",
    vm_no_products: "Walay produkto nga nakit-an.",
    header_search_placeholder: "Mangita og mga produkto…",
    header_vendor_map: "Mapa sa mga Tindera",
    header_my_listings: "Akong mga Listing",
    header_add_listing: "Magdugang og Bag-ong Listing",
    header_login: "Mag-login aron Makabaligya",
    sign_in: "Mag-sign in",
    email_placeholder: "Imong email",
    password_placeholder: "Imong password",
    forgot_password: "nakalimtan ang imong password?",
    processing: "Gi-proseso...",
    log_in: "Mag-login",
    admin_login: "Nag-login isip administrador?",
    auth_modal_title: "Login sa Tindera",
    auth_modal_subtitle:
      "Pamahalaa ang imong ani ug makig-ugnod sa mga kostumer.",
    lf_photo_title: "Litrato sa Produkto",
    lf_photo_sub: "Palihug magdugang og litrato sa imong produkto",
    lf_details_title: "Detalye sa Produkto",
    lf_details_sub: "Isulod ang mga detalye bahin sa imong produkto",
    lf_product_name: "Ngalan sa Produkto",
    lf_product_name_placeholder: "hal. Repolyo, Karot, ug uban pa.",
    lf_quantity: "Kantidad",
    lf_unit: "Yunit",
    lf_product_type: "Klase sa Produkto",
    lf_type_vegetable: "Mga Gulay",
    lf_type_fruit: "Prutas",
    lf_type_chicken: "Manok",
    lf_type_pork: "Baboy",
    lf_type_beef: "Baka",
    lf_type_seafood: "Mga Isda",
    lf_type_rice: "Bugas",
    lf_pricing_title: "Presyo",
    lf_pricing_sub: "Isulod ang orihinal ug discounted nga presyo",
    lf_has_discount: "May diskwento ba ang imong produkto?",
    lf_original_price: "Orihinal nga Presyo",
    lf_discounted_price: "Discounted nga Presyo",
    lf_availability_title: "Availability",
    lf_availability_sub: "Hangtod kanus-a magamit kining listing?",
    lf_availability_window: "Availability Window",
    lf_ends_today: "Matapos Karon",
    lf_1_day: "1 Adlaw",
    lf_2_days: "2 Adlaw",
    lf_3_days: "3 Adlaw",
    li_no_discount: "Walay Diskwento",
    li_sold_out: "Sold Out",
    li_listed: "Gilista",
    li_edit: "I-edit",
    li_mark_sold_out: "Markahan nga Sold Out",
    mi_loading: "Gi-load ang detalye sa tindera...",
    mi_no_photo: "Walay litrato nga nakit-an",
    mi_market_location: "Lokasyon sa Merkado:",
    mi_contact: "Numero sa Kontak:",
    mi_stall_location: "LOKASYON SA TINDAHAN",
    pf_email: "Email Address",
    pf_stall_photo: "Litrato sa Tindahan",
    pf_click_to_upload: "I-click aron mag-upload og litrato",
    pf_stall_name: "Ngalan sa Tindahan",
    pf_market_location: "Lokasyon / Seksyon sa Merkado",
    pf_phone: "Numero sa Telepono",
    pf_what_selling: "Unsa ang imong gibaligya?",
    pf_unselect_all: "I-unselect Tanan",
    pf_select_all: "Pilion Tanan",
    pf_operating_days: "Mga Adlaw sa Operasyon",
    pf_operating_hours: "Oras sa Operasyon",
    pf_creating: "Ginabuhat...",
    pf_saving: "Gina-save...",
    pf_create_profile: "Paghimo og Profile",
    pf_save_profile: "I-save ang Profile",
    vh_vendor_dashboard: "Dashboard sa Tindera",
    vh_marketplace: "Merkado",
    vh_notifications: "Mga Abiso",
    vh_profile: "Profile",
    vh_log_out: "Mag-logout",
    you_are_here: "Naa ka dinhi",
    recenter_label: "I-sentro pag-usab ang mapa sa akong lokasyon",
    recenter_title: "I-sentro pag-usab",
    locating: "Gihanap ang imong lokasyon…",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");
  const t = (key) => translations[lang][key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
