


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_cron" WITH SCHEMA "pg_catalog";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "http" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."deleted_assets" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "bucket_id" "text" NOT NULL,
    "storage_path" "text" NOT NULL,
    "processed" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."deleted_assets" OWNER TO "postgres";


COMMENT ON TABLE "public"."deleted_assets" IS 'Keeps track of all unused image paths for all tables';



ALTER TABLE "public"."deleted_assets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."deleted_assets_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."listing" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "merchant_id" "uuid" NOT NULL,
    "name" character varying NOT NULL,
    "original_price" real DEFAULT '0'::real NOT NULL,
    "image" "text",
    "unit" "text" NOT NULL,
    "quantity" bigint DEFAULT '0'::bigint NOT NULL,
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "discounted_price" real DEFAULT '0'::real NOT NULL
);


ALTER TABLE "public"."listing" OWNER TO "postgres";


COMMENT ON TABLE "public"."listing" IS 'The details of the discounted produce to be sold';



CREATE TABLE IF NOT EXISTS "public"."merchant" (
    "id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying NOT NULL,
    "latitude" numeric NOT NULL,
    "longitude" numeric NOT NULL,
    "location_photo" "text",
    "start_operating_time" time without time zone NOT NULL,
    "end_operating_time" time without time zone NOT NULL,
    "operating_days" character varying[] NOT NULL,
    "location" character varying NOT NULL
);


ALTER TABLE "public"."merchant" OWNER TO "postgres";


ALTER TABLE ONLY "public"."merchant"
    ADD CONSTRAINT "Merchant_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."deleted_assets"
    ADD CONSTRAINT "deleted_assets_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."listing"
    ADD CONSTRAINT "listing_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."merchant"
    ADD CONSTRAINT "Merchant_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."listing"
    ADD CONSTRAINT "listing_merchant_id_fkey" FOREIGN KEY ("merchant_id") REFERENCES "public"."merchant"("id") ON UPDATE CASCADE ON DELETE CASCADE;



CREATE POLICY "Enable delete for users based on user_id" ON "public"."listing" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "merchant_id"));



CREATE POLICY "Enable delete for users based on user_id" ON "public"."merchant" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "id"));



ALTER TABLE "public"."deleted_assets" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."listing" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."merchant" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";




























































































































































































































































GRANT ALL ON TABLE "public"."deleted_assets" TO "anon";
GRANT ALL ON TABLE "public"."deleted_assets" TO "authenticated";
GRANT ALL ON TABLE "public"."deleted_assets" TO "service_role";



GRANT ALL ON SEQUENCE "public"."deleted_assets_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."deleted_assets_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."deleted_assets_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."listing" TO "anon";
GRANT ALL ON TABLE "public"."listing" TO "authenticated";
GRANT ALL ON TABLE "public"."listing" TO "service_role";



GRANT ALL ON TABLE "public"."merchant" TO "anon";
GRANT ALL ON TABLE "public"."merchant" TO "authenticated";
GRANT ALL ON TABLE "public"."merchant" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































