
  create table "public"."schedule" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "merchant_id" uuid not null,
    "day" character varying not null,
    "start_time" time without time zone not null,
    "end_time" time without time zone not null
      );


alter table "public"."schedule" enable row level security;

alter table "public"."merchant" drop column "end_operating_time";

alter table "public"."merchant" drop column "operating_days";

alter table "public"."merchant" drop column "start_operating_time";

CREATE UNIQUE INDEX schedule_pkey ON public.schedule USING btree (id);

alter table "public"."schedule" add constraint "schedule_pkey" PRIMARY KEY using index "schedule_pkey";

alter table "public"."schedule" add constraint "schedule_merchant_id_fkey" FOREIGN KEY (merchant_id) REFERENCES public.merchant(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."schedule" validate constraint "schedule_merchant_id_fkey";

grant delete on table "public"."schedule" to "anon";

grant insert on table "public"."schedule" to "anon";

grant references on table "public"."schedule" to "anon";

grant select on table "public"."schedule" to "anon";

grant trigger on table "public"."schedule" to "anon";

grant truncate on table "public"."schedule" to "anon";

grant update on table "public"."schedule" to "anon";

grant delete on table "public"."schedule" to "authenticated";

grant insert on table "public"."schedule" to "authenticated";

grant references on table "public"."schedule" to "authenticated";

grant select on table "public"."schedule" to "authenticated";

grant trigger on table "public"."schedule" to "authenticated";

grant truncate on table "public"."schedule" to "authenticated";

grant update on table "public"."schedule" to "authenticated";

grant delete on table "public"."schedule" to "service_role";

grant insert on table "public"."schedule" to "service_role";

grant references on table "public"."schedule" to "service_role";

grant select on table "public"."schedule" to "service_role";

grant trigger on table "public"."schedule" to "service_role";

grant truncate on table "public"."schedule" to "service_role";

grant update on table "public"."schedule" to "service_role";


